# config/config.yaml

# Project Configuration
project:
  name: "covid-variant-analysis"
  version: "0.1.0"
  description: "Analysis of SARS-CoV-2 genomic variants using BigQuery"

# BigQuery Settings (using environment variables for sensitive data)
bigquery:
  dataset_id: "covid_variants"
  location: "US"  # BigQuery dataset location

# Data Processing Parameters
data:
  quality:
    min_threshold: 30
    min_depth: 20
  
# Analysis Parameters
analysis:
  significant_pvalue: 0.05
